version: "3.7"                      
                                     
services:        
  tor:                                                                     
    image: test/multiarch-tor:0.4.2.5-rc0
    #build:                 
      #context: tor                   
    networks: 
        main:
          ipv4_address: 172.28.7.10
    # Keep keys in volumes
    volumes:
      - ./tor.yml:/variables.yml:ro
      - tor_hidden_services:/var/lib/tor/onion-services/
      - tor_run_tor:/run/tor

  bitcoind:      
    image: test/multiarch-bitcoind:0.19.0.1-rc0
    #build:
    #  context: bitcoind
    depends_on:  
      - tor  
    #network_mode: container:tor
    networks: 
       main:
          ipv4_address: 172.28.7.20
    environment:                                                           
      BITCOIN_DATA: /home/bitcoin/.bitcoin
      SOCKSPROXY: "127.0.0.1:9050"
    #entrypoint: 
    #  - /wait-for
    #command: "\"tor:9050\" -- /entrypoint.sh bitcoind"
    volumes:
      - bitcoind_data:/home/bitcoin/.bitcoin
      - tor_hidden_services:/run/tor_hidden_services:ro
      - tor_run_tor:/run/tor:ro



volumes:
  tor_hidden_services:
    driver: local
  tor_run_tor:
    driver: local
  bitcoind_data:
    driver: local

networks:
  main:
   ipam:
     config:
       - subnet: 172.28.7.0/24

